#!/bin/bash
# One-time setup: Deploy contract to Sepolia and manage custom image allowlist
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESEARCH_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$RESEARCH_DIR/config.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING:${NC} $1"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR:${NC} $1"; exit 1; }

usage() {
    cat <<EOF
Usage: $0 <command> [options]

Commands:
  deploy              Deploy BaseImageAllowlist contract to Sepolia
  add-image           Add base image using PCR8 + PCR9 (platform-agnostic)
  remove-image        Remove a base image from the allowlist
  set-min-support     Set minimum support level requirement
  set-min-tcb         Set minimum TCB requirement for a platform
  show                Show current config and contract state

Note:
- PCR 8 = kernel cmdline (includes dm-verity hash = launcher identity)
- PCR 9 = GRUB-read files (kernel + initramfs = base image)
- These PCR values are platform-agnostic (same for TDX and SEV-SNP)
- Firmware validation (MRTD/MEASUREMENT) is automatic via Google's endorsements

Options for 'deploy':
  --rpc-url URL       Sepolia RPC URL (default: from config or env)
  --private-key KEY   Private key for deployment (default: from config or env)

Options for 'add-image':
  --pcr8 HASH         PCR 8 value (32 bytes SHA256 hex) - launcher identity
  --pcr9 HASH         PCR 9 value (32 bytes SHA256 hex) - base image identity
  --level LEVEL       Support level: EXPERIMENTAL, USABLE, STABLE, LATEST (default: LATEST)

Options for 'remove-image':
  --pcr8 HASH         PCR 8 value (32 bytes SHA256 hex)
  --pcr9 HASH         PCR 9 value (32 bytes SHA256 hex)

Options for 'set-min-support':
  --level LEVEL       Minimum support level: EXPERIMENTAL, USABLE, STABLE, LATEST

Options for 'set-min-tcb':
  --cvm PLATFORM      CVM platform: tdx or sevsnp (required)
  --tcb NUMBER        Minimum TCB version (uint64)

Examples:
  # Deploy contract
  $0 deploy --rpc-url https://sepolia.infura.io/v3/YOUR_KEY --private-key 0x...

  # Add a custom image (same values work for both TDX and SEV-SNP)
  $0 add-image --pcr8 0x7bf10daf... --pcr9 0xabc123... --level LATEST

  # Set minimum support level to STABLE
  $0 set-min-support --level STABLE

  # Set minimum TCB for TDX
  $0 set-min-tcb --cvm tdx --tcb 3

  # Show current state
  $0 show
EOF
    exit 1
}

load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
    # Environment variables override config file
    SEPOLIA_RPC_URL="${SEPOLIA_RPC_URL:-$RPC_URL}"
    PRIVATE_KEY="${PRIVATE_KEY:-}"
    CONTRACT_ADDR="${CONTRACT_ADDR:-}"
}

save_config() {
    cat > "$CONFIG_FILE" <<EOF
# Research Demo Configuration
# Generated by setup.sh

# Sepolia RPC URL
SEPOLIA_RPC_URL="$SEPOLIA_RPC_URL"

# Contract address (deployed by setup.sh deploy)
CONTRACT_ADDR="$CONTRACT_ADDR"

# Private key - uncomment and set, or use environment variable
# PRIVATE_KEY="0x..."
EOF
    log "Config saved to $CONFIG_FILE"
}

# Convert support level name to uint8
support_level_to_uint8() {
    case "$1" in
        NONE) echo 0 ;;
        EXPERIMENTAL) echo 1 ;;
        USABLE) echo 2 ;;
        STABLE) echo 3 ;;
        LATEST) echo 4 ;;
        *) error "Invalid support level: $1. Must be NONE, EXPERIMENTAL, USABLE, STABLE, or LATEST" ;;
    esac
}

# Convert CVM platform name to uint8
cvm_to_uint8() {
    case "$(echo "$1" | tr '[:upper:]' '[:lower:]')" in
        tdx) echo 0 ;;
        sev-snp|sev_snp|sevsnp) echo 1 ;;
        *) error "Invalid CVM platform: $1. Must be 'tdx' or 'sevsnp'" ;;
    esac
}

deploy_contract() {
    [ -n "$SEPOLIA_RPC_URL" ] || error "SEPOLIA_RPC_URL not set. Use --rpc-url or set environment variable."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set. Use --private-key or set environment variable."

    log "Deploying BaseImageAllowlist contract to Sepolia..."
    log "  RPC URL: $SEPOLIA_RPC_URL"

    cd "$RESEARCH_DIR/contracts"

    # Deploy using forge
    DEPLOY_OUTPUT=$(forge create \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --private-key "$PRIVATE_KEY" \
        --broadcast \
        src/BaseImageAllowlist.sol:BaseImageAllowlist \
        2>&1)

    # Extract contract address from output
    CONTRACT_ADDR=$(echo "$DEPLOY_OUTPUT" | grep -oE "Deployed to: 0x[a-fA-F0-9]{40}" | cut -d' ' -f3)

    if [ -z "$CONTRACT_ADDR" ]; then
        echo "$DEPLOY_OUTPUT"
        error "Failed to extract contract address from deployment output"
    fi

    log "Contract deployed!"
    log "  Address: $CONTRACT_ADDR"

    # Save config
    save_config

    # Verify on Etherscan (optional)
    if [ -n "$ETHERSCAN_API_KEY" ]; then
        log "Verifying contract on Etherscan..."
        forge verify-contract "$CONTRACT_ADDR" \
            src/BaseImageAllowlist.sol:BaseImageAllowlist \
            --chain sepolia \
            --etherscan-api-key "$ETHERSCAN_API_KEY" || warn "Verification failed - you can retry manually"
    else
        log "To verify later, run:"
        log "  ETHERSCAN_API_KEY=... forge verify-contract $CONTRACT_ADDR src/BaseImageAllowlist.sol:BaseImageAllowlist --chain sepolia --etherscan-api-key \$ETHERSCAN_API_KEY"
    fi

    echo ""
    log "Next steps:"
    log "1. Add your custom image (same values work for both TDX and SEV-SNP):"
    log "   $0 add-image --pcr8 0x<pcr8_hex> --pcr9 0x<pcr9_hex> --level LATEST"
    log "2. (Optional) Set minimum support level: $0 set-min-support --level STABLE"
    log "3. (Optional) Set minimum TCB: $0 set-min-tcb --cvm tdx --tcb 3"
    log ""
    log "Note: Firmware validation is automatic - the KMS verifies Google's"
    log "signed endorsements at runtime for both TDX (MRTD) and SEV-SNP (MEASUREMENT)."
}

add_image() {
    local pcr8=""
    local pcr9=""
    local level="LATEST"

    while [[ $# -gt 0 ]]; do
        case $1 in
            --pcr8) pcr8="$2"; shift 2 ;;
            --pcr9) pcr9="$2"; shift 2 ;;
            --level) level="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$pcr8" ] || error "Missing --pcr8 (kernel cmdline / launcher identity)"
    [ -n "$pcr9" ] || error "Missing --pcr9 (GRUB files / base image identity)"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$SEPOLIA_RPC_URL" ] || error "SEPOLIA_RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert level to uint8
    level_uint8=$(support_level_to_uint8 "$level")

    # Normalize hex (ensure 0x prefix, pad to 32 bytes)
    pcr8_hex="0x$(echo "$pcr8" | sed 's/^0x//')"
    pcr9_hex="0x$(echo "$pcr9" | sed 's/^0x//')"

    log "Adding base image to allowlist..."
    log "  PCR8 (launcher): $pcr8_hex"
    log "  PCR9 (base image): $pcr9_hex"
    log "  Support Level: $level ($level_uint8)"
    log "  Contract: $CONTRACT_ADDR"
    log ""
    log "Note: These values are platform-agnostic (same for TDX and SEV-SNP)"

    cast send "$CONTRACT_ADDR" \
        "setImageSupport(bytes32,bytes32,uint8)" \
        "$pcr8_hex" "$pcr9_hex" "$level_uint8" \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Base image added to allowlist!"

    # Verify
    log "Verifying..."
    SUPPORT=$(cast call "$CONTRACT_ADDR" \
        "getImageSupport(bytes32,bytes32)(uint8)" \
        "$pcr8_hex" "$pcr9_hex" \
        --rpc-url "$SEPOLIA_RPC_URL")

    if [ "$SUPPORT" = "$level_uint8" ]; then
        log "Verification passed - image support level is $level"
    else
        error "Verification failed - unexpected support level: $SUPPORT"
    fi
}

remove_image() {
    local pcr8=""
    local pcr9=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --pcr8) pcr8="$2"; shift 2 ;;
            --pcr9) pcr9="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$pcr8" ] || error "Missing --pcr8"
    [ -n "$pcr9" ] || error "Missing --pcr9"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$SEPOLIA_RPC_URL" ] || error "SEPOLIA_RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Normalize hex
    pcr8_hex="0x$(echo "$pcr8" | sed 's/^0x//')"
    pcr9_hex="0x$(echo "$pcr9" | sed 's/^0x//')"

    log "Removing base image from allowlist..."
    log "  PCR8: $pcr8_hex"
    log "  PCR9: $pcr9_hex"
    log "  Contract: $CONTRACT_ADDR"

    cast send "$CONTRACT_ADDR" \
        "removeImage(bytes32,bytes32)" \
        "$pcr8_hex" "$pcr9_hex" \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Base image removed from allowlist!"
}

set_min_support() {
    local level=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --level) level="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$level" ] || error "Missing --level"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$SEPOLIA_RPC_URL" ] || error "SEPOLIA_RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert level to uint8
    level_uint8=$(support_level_to_uint8 "$level")

    log "Setting minimum support level..."
    log "  Level: $level ($level_uint8)"
    log "  Contract: $CONTRACT_ADDR"

    cast send "$CONTRACT_ADDR" \
        "setMinimumSupportLevel(uint8)" \
        "$level_uint8" \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Minimum support level set to $level!"
}

set_min_tcb() {
    local cvm=""
    local tcb=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --cvm) cvm="$2"; shift 2 ;;
            --tcb) tcb="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$cvm" ] || error "Missing --cvm (tdx or sevsnp)"
    [ -n "$tcb" ] || error "Missing --tcb"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$SEPOLIA_RPC_URL" ] || error "SEPOLIA_RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert CVM to uint8
    cvm_uint8=$(cvm_to_uint8 "$cvm")

    log "Setting minimum TCB for $cvm..."
    log "  CVM: $cvm ($cvm_uint8)"
    log "  TCB: $tcb"
    log "  Contract: $CONTRACT_ADDR"

    cast send "$CONTRACT_ADDR" \
        "setMinimumTcb(uint8,uint64)" \
        "$cvm_uint8" "$tcb" \
        --rpc-url "$SEPOLIA_RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Minimum TCB for $cvm set to $tcb!"
}

show_config() {
    log "Current Configuration:"
    echo ""
    echo "  Config file: $CONFIG_FILE"
    echo "  SEPOLIA_RPC_URL: ${SEPOLIA_RPC_URL:-<not set>}"
    echo "  CONTRACT_ADDR: ${CONTRACT_ADDR:-<not set>}"
    echo "  PRIVATE_KEY: ${PRIVATE_KEY:+<set>}${PRIVATE_KEY:-<not set>}"

    if [ -n "$CONTRACT_ADDR" ] && [ -n "$SEPOLIA_RPC_URL" ]; then
        echo ""
        log "Contract State:"
        OWNER=$(cast call "$CONTRACT_ADDR" "owner()(address)" --rpc-url "$SEPOLIA_RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  Owner: $OWNER"

        MIN_SUPPORT=$(cast call "$CONTRACT_ADDR" "minimumSupportLevel()(uint8)" --rpc-url "$SEPOLIA_RPC_URL" 2>/dev/null || echo "<unable to query>")
        SUPPORT_NAMES=("NONE" "EXPERIMENTAL" "USABLE" "STABLE" "LATEST")
        if [[ "$MIN_SUPPORT" =~ ^[0-4]$ ]]; then
            echo "  Minimum Support Level: ${SUPPORT_NAMES[$MIN_SUPPORT]} ($MIN_SUPPORT)"
        else
            echo "  Minimum Support Level: $MIN_SUPPORT"
        fi

        echo ""
        log "Per-CVM Minimum TCB:"
        TDX_TCB=$(cast call "$CONTRACT_ADDR" "minimumTcb(uint8)(uint64)" 0 --rpc-url "$SEPOLIA_RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  TDX: $TDX_TCB"
        SEVSNP_TCB=$(cast call "$CONTRACT_ADDR" "minimumTcb(uint8)(uint64)" 1 --rpc-url "$SEPOLIA_RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  SEV-SNP: $SEVSNP_TCB"

        echo ""
        log "Firmware validation:"
        echo "  Verified automatically against Google's signed endorsements"
        echo "  TDX: gs://gce_tcb_integrity/ovmf_x64_csm/tdx/"
        echo "  SEV-SNP: gs://gce_tcb_integrity/ovmf_x64_csm/sevsnp/"
        echo ""
        log "To check specific image (platform-agnostic - same for TDX and SEV-SNP):"
        echo "  cast call $CONTRACT_ADDR 'getImageSupport(bytes32,bytes32)(uint8)' 0x<pcr8> 0x<pcr9> --rpc-url \$SEPOLIA_RPC_URL"
    fi
}

# Main
load_config

case "${1:-}" in
    deploy)
        shift
        while [[ $# -gt 0 ]]; do
            case $1 in
                --rpc-url) SEPOLIA_RPC_URL="$2"; shift 2 ;;
                --private-key) PRIVATE_KEY="$2"; shift 2 ;;
                *) error "Unknown option: $1" ;;
            esac
        done
        deploy_contract
        ;;
    add-image)
        shift
        add_image "$@"
        ;;
    remove-image)
        shift
        remove_image "$@"
        ;;
    set-min-support)
        shift
        set_min_support "$@"
        ;;
    set-min-tcb)
        shift
        set_min_tcb "$@"
        ;;
    show)
        show_config
        ;;
    *)
        usage
        ;;
esac
