#!/bin/bash
# One-time setup: Deploy contract to Sepolia and manage custom image allowlist
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESEARCH_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$RESEARCH_DIR/config.env"
EIGENX_CONTRACTS_DIR="${EIGENX_CONTRACTS_DIR:-/Users/cavan/source/eigenx-contracts}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING:${NC} $1"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR:${NC} $1"; exit 1; }

usage() {
    cat <<EOF
Usage: $0 <command> [options]

Commands:
  deploy              Deploy ImageAllowlist contract
  add-image           Add base image using PCR measurements from JSON file
  remove-image        Remove a base image from the allowlist
  set-min-tcb         Set minimum TCB requirement for a platform
  show                Show current config and contract state

Note:
- Images are stored per-CVM (separate allowlists for TDX and SEV-SNP)
- Common PCRs: 4 (EFI boot apps), 8 (launcher identity), 9 (base image)
- Firmware validation (MRTD/MEASUREMENT) is automatic via Google's endorsements

Options for 'deploy':
  --rpc-url URL       RPC URL (default: from config or env)
  --private-key KEY   Private key for deployment (default: from config or env)

Environment variables:
  EIGENX_CONTRACTS_DIR  Path to eigenx-contracts repo (default: /Users/cavan/source/eigenx-contracts)

Options for 'add-image':
  --cvm PLATFORM      CVM platform: tdx or sevsnp (required)
  --pcrs FILE         JSON file with PCR measurements (required)

Options for 'remove-image':
  --cvm PLATFORM      CVM platform: tdx or sevsnp (required)
  --pcrs FILE         JSON file with PCR measurements (required)

Options for 'set-min-tcb':
  --cvm PLATFORM      CVM platform: tdx or sevsnp (required)
  --tcb NUMBER        Minimum TCB version (uint64)

JSON file format for PCRs:
  {
    "pcrs": [
      {"index": 4, "value": "0x1234abcd..."},
      {"index": 8, "value": "0x7bf10daf..."},
      {"index": 9, "value": "0xabc123..."}
    ]
  }

Examples:
  # Deploy contract (local anvil)
  $0 deploy --rpc-url http://127.0.0.1:8545 --private-key 0x...

  # Add a custom image for TDX
  $0 add-image --cvm tdx --pcrs image-pcrs.json

  # Add a custom image for SEV-SNP
  $0 add-image --cvm sevsnp --pcrs image-pcrs.json

  # Set minimum TCB for TDX
  $0 set-min-tcb --cvm tdx --tcb 3

  # Show current state
  $0 show
EOF
    exit 1
}

load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
    # Environment variables override config file
    RPC_URL="${RPC_URL:-}"
    PRIVATE_KEY="${PRIVATE_KEY:-}"
    CONTRACT_ADDR="${CONTRACT_ADDR:-}"
}

save_config() {
    cat > "$CONFIG_FILE" <<EOF
# Research Demo Configuration
# Generated by setup.sh

# RPC URL
RPC_URL="$RPC_URL"

# Contract address (deployed by setup.sh deploy)
CONTRACT_ADDR="$CONTRACT_ADDR"

# Private key - uncomment and set, or use environment variable
# PRIVATE_KEY="0x..."
EOF
    log "Config saved to $CONFIG_FILE"
}

# Convert CVM platform name to uint8
cvm_to_uint8() {
    case "$(echo "$1" | tr '[:upper:]' '[:lower:]')" in
        tdx) echo 0 ;;
        sev-snp|sev_snp|sevsnp) echo 1 ;;
        *) error "Invalid CVM platform: $1. Must be 'tdx' or 'sevsnp'" ;;
    esac
}

deploy_contract() {
    [ -n "$RPC_URL" ] || error "RPC_URL not set. Use --rpc-url or set environment variable."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set. Use --private-key or set environment variable."
    [ -d "$EIGENX_CONTRACTS_DIR" ] || error "eigenx-contracts not found at $EIGENX_CONTRACTS_DIR. Set EIGENX_CONTRACTS_DIR."

    # Get deployer address from private key
    DEPLOYER_ADDR=$(cast wallet address "$PRIVATE_KEY")

    log "Deploying ImageAllowlist contract..."
    log "  RPC URL: $RPC_URL"
    log "  Owner: $DEPLOYER_ADDR"

    cd "$EIGENX_CONTRACTS_DIR"

    # Build verify flags if API key is set
    VERIFY_FLAGS=""
    if [ -n "$ETHERSCAN_API_KEY" ]; then
        log "  Etherscan verification: enabled"
        VERIFY_FLAGS="--verify --etherscan-api-key $ETHERSCAN_API_KEY"
    fi

    # Deploy using forge script (proxy admin = 0x0 means create new one)
    DEPLOY_OUTPUT=$(forge script script/DeployImageAllowlist.s.sol \
        --sig "run(address,address)" \
        "0x0000000000000000000000000000000000000000" \
        "$DEPLOYER_ADDR" \
        --rpc-url "$RPC_URL" \
        --private-key "$PRIVATE_KEY" \
        --broadcast \
        $VERIFY_FLAGS \
        2>&1)

    # Extract addresses from output
    CONTRACT_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "ImageAllowlist proxy:" | grep -oE "0x[a-fA-F0-9]{40}")
    IMPL_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "ImageAllowlist implementation:" | grep -oE "0x[a-fA-F0-9]{40}")

    if [ -z "$CONTRACT_ADDR" ]; then
        echo "$DEPLOY_OUTPUT"
        error "Failed to extract contract address from deployment output"
    fi

    log "Contract deployed!"
    log "  Proxy Address: $CONTRACT_ADDR"
    log "  Implementation: $IMPL_ADDR"

    # Save config
    save_config

    echo ""
    log "Next steps:"
    log "1. Create a JSON file with your image's PCR values:"
    log "   echo '{\"pcrs\": [{\"index\": 4, \"value\": \"0x...\"}, {\"index\": 8, \"value\": \"0x...\"}, {\"index\": 9, \"value\": \"0x...\"}]}' > image-pcrs.json"
    log "2. Add your custom image for TDX: $0 add-image --cvm tdx --pcrs image-pcrs.json"
    log "3. Add your custom image for SEV-SNP: $0 add-image --cvm sevsnp --pcrs image-pcrs.json"
    log "4. (Optional) Set minimum TCB: $0 set-min-tcb --cvm tdx --tcb 3"
    log ""
    log "Note: Firmware validation is automatic - the KMS verifies Google's"
    log "signed endorsements at runtime for both TDX (MRTD) and SEV-SNP (MEASUREMENT)."
}

add_image() {
    local cvm=""
    local pcrs_file=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --cvm) cvm="$2"; shift 2 ;;
            --pcrs) pcrs_file="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$cvm" ] || error "Missing --cvm (tdx or sevsnp)"
    [ -n "$pcrs_file" ] || error "Missing --pcrs <file.json>"
    [ -f "$pcrs_file" ] || error "PCRs file not found: $pcrs_file"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$RPC_URL" ] || error "RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert CVM to uint8
    cvm_uint8=$(cvm_to_uint8 "$cvm")

    # Parse JSON and build PCR tuple array for cast
    # Format: [(index1,value1),(index2,value2),...]
    pcr_tuples=$(jq -r '.pcrs | sort_by(.index) | map("(\(.index),\(.value))") | join(",")' "$pcrs_file")
    [ -n "$pcr_tuples" ] || error "Failed to parse PCRs from $pcrs_file"

    log "Adding base image to allowlist..."
    log "  CVM: $cvm ($cvm_uint8)"
    log "  PCRs file: $pcrs_file"
    # Show individual PCRs
    jq -r '.pcrs | sort_by(.index)[] | "  PCR\(.index): \(.value)"' "$pcrs_file"
    log "  Contract: $CONTRACT_ADDR"

    cast send "$CONTRACT_ADDR" \
        "setImage(uint8,(uint8,bytes32)[],bool)" \
        "$cvm_uint8" "[$pcr_tuples]" "true" \
        --rpc-url "$RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Base image added to $cvm allowlist!"

    # Verify
    log "Verifying..."
    ALLOWED=$(cast call "$CONTRACT_ADDR" \
        "isImageAllowed(uint8,(uint8,bytes32)[])(bool)" \
        "$cvm_uint8" "[$pcr_tuples]" \
        --rpc-url "$RPC_URL")

    if [ "$ALLOWED" = "true" ]; then
        log "Verification passed - image is allowed for $cvm"
    else
        error "Verification failed - image not allowed"
    fi
}

remove_image() {
    local cvm=""
    local pcrs_file=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --cvm) cvm="$2"; shift 2 ;;
            --pcrs) pcrs_file="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$cvm" ] || error "Missing --cvm (tdx or sevsnp)"
    [ -n "$pcrs_file" ] || error "Missing --pcrs <file.json>"
    [ -f "$pcrs_file" ] || error "PCRs file not found: $pcrs_file"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$RPC_URL" ] || error "RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert CVM to uint8
    cvm_uint8=$(cvm_to_uint8 "$cvm")

    # Parse JSON and build PCR tuple array for cast
    pcr_tuples=$(jq -r '.pcrs | sort_by(.index) | map("(\(.index),\(.value))") | join(",")' "$pcrs_file")
    [ -n "$pcr_tuples" ] || error "Failed to parse PCRs from $pcrs_file"

    log "Removing base image from allowlist..."
    log "  CVM: $cvm ($cvm_uint8)"
    log "  PCRs file: $pcrs_file"
    jq -r '.pcrs | sort_by(.index)[] | "  PCR\(.index): \(.value)"' "$pcrs_file"
    log "  Contract: $CONTRACT_ADDR"

    # Set allowed to false to remove from allowlist
    cast send "$CONTRACT_ADDR" \
        "setImage(uint8,(uint8,bytes32)[],bool)" \
        "$cvm_uint8" "[$pcr_tuples]" "false" \
        --rpc-url "$RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Base image removed from $cvm allowlist!"
}

set_min_tcb() {
    local cvm=""
    local tcb=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --cvm) cvm="$2"; shift 2 ;;
            --tcb) tcb="$2"; shift 2 ;;
            *) error "Unknown option: $1" ;;
        esac
    done

    [ -n "$cvm" ] || error "Missing --cvm (tdx or sevsnp)"
    [ -n "$tcb" ] || error "Missing --tcb"
    [ -n "$CONTRACT_ADDR" ] || error "CONTRACT_ADDR not set. Run 'deploy' first."
    [ -n "$RPC_URL" ] || error "RPC_URL not set."
    [ -n "$PRIVATE_KEY" ] || error "PRIVATE_KEY not set."

    # Convert CVM to uint8
    cvm_uint8=$(cvm_to_uint8 "$cvm")

    log "Setting minimum TCB for $cvm..."
    log "  CVM: $cvm ($cvm_uint8)"
    log "  TCB: $tcb"
    log "  Contract: $CONTRACT_ADDR"

    cast send "$CONTRACT_ADDR" \
        "setMinimumTCB(uint8,uint64)" \
        "$cvm_uint8" "$tcb" \
        --rpc-url "$RPC_URL" \
        --private-key "$PRIVATE_KEY"

    log "Minimum TCB for $cvm set to $tcb!"
}

show_config() {
    log "Current Configuration:"
    echo ""
    echo "  Config file: $CONFIG_FILE"
    echo "  RPC_URL: ${RPC_URL:-<not set>}"
    echo "  CONTRACT_ADDR: ${CONTRACT_ADDR:-<not set>}"
    echo "  PRIVATE_KEY: ${PRIVATE_KEY:+<set>}${PRIVATE_KEY:-<not set>}"

    if [ -n "$CONTRACT_ADDR" ] && [ -n "$RPC_URL" ]; then
        echo ""
        log "Contract State:"
        OWNER=$(cast call "$CONTRACT_ADDR" "owner()(address)" --rpc-url "$RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  Owner: $OWNER"

        echo ""
        log "Per-CVM Minimum TCB:"
        TDX_TCB=$(cast call "$CONTRACT_ADDR" "minimumTCB(uint8)(uint64)" 0 --rpc-url "$RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  TDX: $TDX_TCB"
        SEVSNP_TCB=$(cast call "$CONTRACT_ADDR" "minimumTCB(uint8)(uint64)" 1 --rpc-url "$RPC_URL" 2>/dev/null || echo "<unable to query>")
        echo "  SEV-SNP: $SEVSNP_TCB"

        echo ""
        log "Firmware validation:"
        echo "  Verified automatically against Google's signed endorsements"
        echo "  TDX: gs://gce_tcb_integrity/ovmf_x64_csm/tdx/"
        echo "  SEV-SNP: gs://gce_tcb_integrity/ovmf_x64_csm/sevsnp/"
        echo ""
        log "To check specific image (per-CVM storage):"
        echo "  # For TDX:"
        echo "  cast call $CONTRACT_ADDR 'isImageAllowed(uint8,(uint8,bytes32)[])(bool)' 0 '[(4,0x<pcr4>),(8,0x<pcr8>),(9,0x<pcr9>)]' --rpc-url \$RPC_URL"
        echo "  # For SEV-SNP:"
        echo "  cast call $CONTRACT_ADDR 'isImageAllowed(uint8,(uint8,bytes32)[])(bool)' 1 '[(4,0x<pcr4>),(8,0x<pcr8>),(9,0x<pcr9>)]' --rpc-url \$RPC_URL"
    fi
}

# Main
load_config

case "${1:-}" in
    deploy)
        shift
        while [[ $# -gt 0 ]]; do
            case $1 in
                --rpc-url) RPC_URL="$2"; shift 2 ;;
                --private-key) PRIVATE_KEY="$2"; shift 2 ;;
                *) error "Unknown option: $1" ;;
            esac
        done
        deploy_contract
        ;;
    add-image)
        shift
        add_image "$@"
        ;;
    remove-image)
        shift
        remove_image "$@"
        ;;
    set-min-tcb)
        shift
        set_min_tcb "$@"
        ;;
    show)
        show_config
        ;;
    *)
        usage
        ;;
esac
