// Endorsement protobuf definitions from gce-tcb-verifier.
// Source: github.com/google/gce-tcb-verifier/proto/endorsement/endorsement.proto

// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file endorsement.proto (package cloud_vmm_proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file endorsement.proto.
 */
export const file_endorsement: GenFile = /*@__PURE__*/
  fileDesc("ChFlbmRvcnNlbWVudC5wcm90bxIPY2xvdWRfdm1tX3Byb3RvIkgKE1ZNTGF1bmNoRW5kb3JzZW1lbnQSHgoWc2VyaWFsaXplZF91ZWZpX2dvbGRlbhgBIAEoDBIRCglzaWduYXR1cmUYAiABKAwi5wEKE1ZNR29sZGVuTWVhc3VyZW1lbnQSLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIPCgdjbF9zcGVjGAIgASgEEg4KBmNvbW1pdBgDIAEoDBIMCgRjZXJ0GAQgASgMEg4KBmRpZ2VzdBgFIAEoDBIRCgljYV9idW5kbGUYBiABKAwSKgoHc2V2X3NucBgHIAEoCzIZLmNsb3VkX3ZtbV9wcm90by5WTVNldlNucBIjCgN0ZHgYCCABKAsyFi5jbG91ZF92bW1fcHJvdG8uVk1UZHgi8QEKCFZNU2V2U25wEgsKA3N2bhgBIAEoDRJBCgxtZWFzdXJlbWVudHMYAiADKAsyKy5jbG91ZF92bW1fcHJvdG8uVk1TZXZTbnAuTWVhc3VyZW1lbnRzRW50cnkSEQoJZmFtaWx5X2lkGAMgASgMEhAKCGltYWdlX2lkGAQgASgMEg4KBnBvbGljeRgFIAEoBBIRCgljYV9idW5kbGUYBiABKAwSGAoQc3ZzbV9tZWFzdXJlbWVudBgHIAEoDBozChFNZWFzdXJlbWVudHNFbnRyeRILCgNrZXkYASABKA0SDQoFdmFsdWUYAiABKAw6AjgBIpIBCgVWTVRkeBILCgNzdm4YASABKA0SOAoMbWVhc3VyZW1lbnRzGAIgAygLMiIuY2xvdWRfdm1tX3Byb3RvLlZNVGR4Lk1lYXN1cmVtZW50GkIKC01lYXN1cmVtZW50Eg8KB3JhbV9naWIYASABKA0SFAoMZWFybHlfYWNjZXB0GAIgASgIEgwKBG1ydGQYAyABKAxiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message cloud_vmm_proto.VMLaunchEndorsement
 */
export type VMLaunchEndorsement = Message<"cloud_vmm_proto.VMLaunchEndorsement"> & {
  /**
   * @generated from field: bytes serialized_uefi_golden = 1;
   */
  serializedUefiGolden: Uint8Array;

  /**
   * @generated from field: bytes signature = 2;
   */
  signature: Uint8Array;
};

/**
 * Describes the message cloud_vmm_proto.VMLaunchEndorsement.
 * Use `create(VMLaunchEndorsementSchema)` to create a new message.
 */
export const VMLaunchEndorsementSchema: GenMessage<VMLaunchEndorsement> = /*@__PURE__*/
  messageDesc(file_endorsement, 0);

/**
 * @generated from message cloud_vmm_proto.VMGoldenMeasurement
 */
export type VMGoldenMeasurement = Message<"cloud_vmm_proto.VMGoldenMeasurement"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: uint64 cl_spec = 2;
   */
  clSpec: bigint;

  /**
   * @generated from field: bytes commit = 3;
   */
  commit: Uint8Array;

  /**
   * DER format certificate of the key that signed this document.
   *
   * @generated from field: bytes cert = 4;
   */
  cert: Uint8Array;

  /**
   * SHA-384 digest of the UEFI binary without TEE-specifics about launch.
   *
   * @generated from field: bytes digest = 5;
   */
  digest: Uint8Array;

  /**
   * PEM-encoded certificates of keys used in cert in Root ... final intermediate order.
   *
   * @generated from field: bytes ca_bundle = 6;
   */
  caBundle: Uint8Array;

  /**
   * @generated from field: cloud_vmm_proto.VMSevSnp sev_snp = 7;
   */
  sevSnp?: VMSevSnp;

  /**
   * @generated from field: cloud_vmm_proto.VMTdx tdx = 8;
   */
  tdx?: VMTdx;
};

/**
 * Describes the message cloud_vmm_proto.VMGoldenMeasurement.
 * Use `create(VMGoldenMeasurementSchema)` to create a new message.
 */
export const VMGoldenMeasurementSchema: GenMessage<VMGoldenMeasurement> = /*@__PURE__*/
  messageDesc(file_endorsement, 1);

/**
 * @generated from message cloud_vmm_proto.VMSevSnp
 */
export type VMSevSnp = Message<"cloud_vmm_proto.VMSevSnp"> & {
  /**
   * @generated from field: uint32 svn = 1;
   */
  svn: number;

  /**
   * Expected MEASUREMENT report field values given [key]-many VMSAs at launch.
   *
   * @generated from field: map<uint32, bytes> measurements = 2;
   */
  measurements: { [key: number]: Uint8Array };

  /**
   * @generated from field: bytes family_id = 3;
   */
  familyId: Uint8Array;

  /**
   * @generated from field: bytes image_id = 4;
   */
  imageId: Uint8Array;

  /**
   * @generated from field: uint64 policy = 5;
   */
  policy: bigint;

  /**
   * @generated from field: bytes ca_bundle = 6;
   */
  caBundle: Uint8Array;

  /**
   * @generated from field: bytes svsm_measurement = 7;
   */
  svsmMeasurement: Uint8Array;
};

/**
 * Describes the message cloud_vmm_proto.VMSevSnp.
 * Use `create(VMSevSnpSchema)` to create a new message.
 */
export const VMSevSnpSchema: GenMessage<VMSevSnp> = /*@__PURE__*/
  messageDesc(file_endorsement, 2);

/**
 * @generated from message cloud_vmm_proto.VMTdx
 */
export type VMTdx = Message<"cloud_vmm_proto.VMTdx"> & {
  /**
   * @generated from field: uint32 svn = 1;
   */
  svn: number;

  /**
   * @generated from field: repeated cloud_vmm_proto.VMTdx.Measurement measurements = 2;
   */
  measurements: VMTdx_Measurement[];
};

/**
 * Describes the message cloud_vmm_proto.VMTdx.
 * Use `create(VMTdxSchema)` to create a new message.
 */
export const VMTdxSchema: GenMessage<VMTdx> = /*@__PURE__*/
  messageDesc(file_endorsement, 3);

/**
 * @generated from message cloud_vmm_proto.VMTdx.Measurement
 */
export type VMTdx_Measurement = Message<"cloud_vmm_proto.VMTdx.Measurement"> & {
  /**
   * @generated from field: uint32 ram_gib = 1;
   */
  ramGib: number;

  /**
   * @generated from field: bool early_accept = 2;
   */
  earlyAccept: boolean;

  /**
   * @generated from field: bytes mrtd = 3;
   */
  mrtd: Uint8Array;
};

/**
 * Describes the message cloud_vmm_proto.VMTdx.Measurement.
 * Use `create(VMTdx_MeasurementSchema)` to create a new message.
 */
export const VMTdx_MeasurementSchema: GenMessage<VMTdx_Measurement> = /*@__PURE__*/
  messageDesc(file_endorsement, 3, 0);

