// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file sevsnp.proto (package sevsnp, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sevsnp.proto.
 */
export const file_sevsnp: GenFile = /*@__PURE__*/
  fileDesc("CgxzZXZzbnAucHJvdG8SBnNldnNucCKjBQoGUmVwb3J0Eg8KB3ZlcnNpb24YASABKA0SEQoJZ3Vlc3Rfc3ZuGAIgASgNEg4KBnBvbGljeRgDIAEoBBIRCglmYW1pbHlfaWQYBCABKAwSEAoIaW1hZ2VfaWQYBSABKAwSDAoEdm1wbBgGIAEoDRIWCg5zaWduYXR1cmVfYWxnbxgHIAEoDRITCgtjdXJyZW50X3RjYhgIIAEoBBIVCg1wbGF0Zm9ybV9pbmZvGAkgASgEEhMKC3NpZ25lcl9pbmZvGAogASgNEhMKC3JlcG9ydF9kYXRhGAsgASgMEhMKC21lYXN1cmVtZW50GAwgASgMEhEKCWhvc3RfZGF0YRgNIAEoDBIVCg1pZF9rZXlfZGlnZXN0GA4gASgMEhkKEWF1dGhvcl9rZXlfZGlnZXN0GA8gASgMEhEKCXJlcG9ydF9pZBgQIAEoDBIUCgxyZXBvcnRfaWRfbWEYESABKAwSFAoMcmVwb3J0ZWRfdGNiGBIgASgEEg8KB2NoaXBfaWQYEyABKAwSFQoNY29tbWl0dGVkX3RjYhgUIAEoBBIVCg1jdXJyZW50X2J1aWxkGBUgASgNEhUKDWN1cnJlbnRfbWlub3IYFiABKA0SFQoNY3VycmVudF9tYWpvchgXIAEoDRIXCg9jb21taXR0ZWRfYnVpbGQYGCABKA0SFwoPY29tbWl0dGVkX21pbm9yGBkgASgNEhcKD2NvbW1pdHRlZF9tYWpvchgaIAEoDRISCgpsYXVuY2hfdGNiGBsgASgEEhEKCXNpZ25hdHVyZRgcIAEoDBIVCg1jcHVpZDFlYXhfZm1zGB0gASgNEhkKEWxhdW5jaF9taXRfdmVjdG9yGB4gASgEEhoKEmN1cnJlbnRfbWl0X3ZlY3RvchgfIAEoBCLcAQoQQ2VydGlmaWNhdGVDaGFpbhIRCgl2Y2VrX2NlcnQYASABKAwSEQoJdmxla19jZXJ0GAYgASgMEhAKCGFza19jZXJ0GAIgASgMEhAKCGFya19jZXJ0GAMgASgMEhkKDWZpcm13YXJlX2NlcnQYBCABKAxCAhgBEjQKBmV4dHJhcxgHIAMoCzIkLnNldnNucC5DZXJ0aWZpY2F0ZUNoYWluLkV4dHJhc0VudHJ5Gi0KC0V4dHJhc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoDDoCOAEiwwEKClNldlByb2R1Y3QSLwoEbmFtZRgBIAEoDjIhLnNldnNucC5TZXZQcm9kdWN0LlNldlByb2R1Y3ROYW1lEhQKCHN0ZXBwaW5nGAIgASgNQgIYASJuCg5TZXZQcm9kdWN0TmFtZRIXChNTRVZfUFJPRFVDVF9VTktOT1dOEAASFQoRU0VWX1BST0RVQ1RfTUlMQU4QARIVChFTRVZfUFJPRFVDVF9HRU5PQRACEhUKEVNFVl9QUk9EVUNUX1RVUklOEAMihwEKC0F0dGVzdGF0aW9uEh4KBnJlcG9ydBgBIAEoCzIOLnNldnNucC5SZXBvcnQSMwoRY2VydGlmaWNhdGVfY2hhaW4YAiABKAsyGC5zZXZzbnAuQ2VydGlmaWNhdGVDaGFpbhIjCgdwcm9kdWN0GAMgASgLMhIuc2V2c25wLlNldlByb2R1Y3RiBnByb3RvMw");

/**
 * @generated from message sevsnp.Report
 */
export type Report = Message<"sevsnp.Report"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from field: uint32 guest_svn = 2;
   */
  guestSvn: number;

  /**
   * @generated from field: uint64 policy = 3;
   */
  policy: bigint;

  /**
   * @generated from field: bytes family_id = 4;
   */
  familyId: Uint8Array;

  /**
   * @generated from field: bytes image_id = 5;
   */
  imageId: Uint8Array;

  /**
   * @generated from field: uint32 vmpl = 6;
   */
  vmpl: number;

  /**
   * @generated from field: uint32 signature_algo = 7;
   */
  signatureAlgo: number;

  /**
   * @generated from field: uint64 current_tcb = 8;
   */
  currentTcb: bigint;

  /**
   * @generated from field: uint64 platform_info = 9;
   */
  platformInfo: bigint;

  /**
   * @generated from field: uint32 signer_info = 10;
   */
  signerInfo: number;

  /**
   * @generated from field: bytes report_data = 11;
   */
  reportData: Uint8Array;

  /**
   * @generated from field: bytes measurement = 12;
   */
  measurement: Uint8Array;

  /**
   * @generated from field: bytes host_data = 13;
   */
  hostData: Uint8Array;

  /**
   * @generated from field: bytes id_key_digest = 14;
   */
  idKeyDigest: Uint8Array;

  /**
   * @generated from field: bytes author_key_digest = 15;
   */
  authorKeyDigest: Uint8Array;

  /**
   * @generated from field: bytes report_id = 16;
   */
  reportId: Uint8Array;

  /**
   * @generated from field: bytes report_id_ma = 17;
   */
  reportIdMa: Uint8Array;

  /**
   * @generated from field: uint64 reported_tcb = 18;
   */
  reportedTcb: bigint;

  /**
   * @generated from field: bytes chip_id = 19;
   */
  chipId: Uint8Array;

  /**
   * @generated from field: uint64 committed_tcb = 20;
   */
  committedTcb: bigint;

  /**
   * @generated from field: uint32 current_build = 21;
   */
  currentBuild: number;

  /**
   * @generated from field: uint32 current_minor = 22;
   */
  currentMinor: number;

  /**
   * @generated from field: uint32 current_major = 23;
   */
  currentMajor: number;

  /**
   * @generated from field: uint32 committed_build = 24;
   */
  committedBuild: number;

  /**
   * @generated from field: uint32 committed_minor = 25;
   */
  committedMinor: number;

  /**
   * @generated from field: uint32 committed_major = 26;
   */
  committedMajor: number;

  /**
   * @generated from field: uint64 launch_tcb = 27;
   */
  launchTcb: bigint;

  /**
   * @generated from field: bytes signature = 28;
   */
  signature: Uint8Array;

  /**
   * @generated from field: uint32 cpuid1eax_fms = 29;
   */
  cpuid1eaxFms: number;

  /**
   * @generated from field: uint64 launch_mit_vector = 30;
   */
  launchMitVector: bigint;

  /**
   * @generated from field: uint64 current_mit_vector = 31;
   */
  currentMitVector: bigint;
};

/**
 * Describes the message sevsnp.Report.
 * Use `create(ReportSchema)` to create a new message.
 */
export const ReportSchema: GenMessage<Report> = /*@__PURE__*/
  messageDesc(file_sevsnp, 0);

/**
 * @generated from message sevsnp.CertificateChain
 */
export type CertificateChain = Message<"sevsnp.CertificateChain"> & {
  /**
   * @generated from field: bytes vcek_cert = 1;
   */
  vcekCert: Uint8Array;

  /**
   * @generated from field: bytes vlek_cert = 6;
   */
  vlekCert: Uint8Array;

  /**
   * @generated from field: bytes ask_cert = 2;
   */
  askCert: Uint8Array;

  /**
   * @generated from field: bytes ark_cert = 3;
   */
  arkCert: Uint8Array;

  /**
   * @generated from field: bytes firmware_cert = 4 [deprecated = true];
   * @deprecated
   */
  firmwareCert: Uint8Array;

  /**
   * @generated from field: map<string, bytes> extras = 7;
   */
  extras: { [key: string]: Uint8Array };
};

/**
 * Describes the message sevsnp.CertificateChain.
 * Use `create(CertificateChainSchema)` to create a new message.
 */
export const CertificateChainSchema: GenMessage<CertificateChain> = /*@__PURE__*/
  messageDesc(file_sevsnp, 1);

/**
 * @generated from message sevsnp.SevProduct
 */
export type SevProduct = Message<"sevsnp.SevProduct"> & {
  /**
   * @generated from field: sevsnp.SevProduct.SevProductName name = 1;
   */
  name: SevProduct_SevProductName;

  /**
   * @generated from field: uint32 stepping = 2 [deprecated = true];
   * @deprecated
   */
  stepping: number;
};

/**
 * Describes the message sevsnp.SevProduct.
 * Use `create(SevProductSchema)` to create a new message.
 */
export const SevProductSchema: GenMessage<SevProduct> = /*@__PURE__*/
  messageDesc(file_sevsnp, 2);

/**
 * @generated from enum sevsnp.SevProduct.SevProductName
 */
export enum SevProduct_SevProductName {
  /**
   * @generated from enum value: SEV_PRODUCT_UNKNOWN = 0;
   */
  SEV_PRODUCT_UNKNOWN = 0,

  /**
   * @generated from enum value: SEV_PRODUCT_MILAN = 1;
   */
  SEV_PRODUCT_MILAN = 1,

  /**
   * @generated from enum value: SEV_PRODUCT_GENOA = 2;
   */
  SEV_PRODUCT_GENOA = 2,

  /**
   * @generated from enum value: SEV_PRODUCT_TURIN = 3;
   */
  SEV_PRODUCT_TURIN = 3,
}

/**
 * Describes the enum sevsnp.SevProduct.SevProductName.
 */
export const SevProduct_SevProductNameSchema: GenEnum<SevProduct_SevProductName> = /*@__PURE__*/
  enumDesc(file_sevsnp, 2, 0);

/**
 * @generated from message sevsnp.Attestation
 */
export type Attestation = Message<"sevsnp.Attestation"> & {
  /**
   * @generated from field: sevsnp.Report report = 1;
   */
  report?: Report;

  /**
   * @generated from field: sevsnp.CertificateChain certificate_chain = 2;
   */
  certificateChain?: CertificateChain;

  /**
   * @generated from field: sevsnp.SevProduct product = 3;
   */
  product?: SevProduct;
};

/**
 * Describes the message sevsnp.Attestation.
 * Use `create(AttestationSchema)` to create a new message.
 */
export const AttestationSchema: GenMessage<Attestation> = /*@__PURE__*/
  messageDesc(file_sevsnp, 3);

