// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file tdx.proto (package tdx, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tdx.proto.
 */
export const file_tdx: GenFile = /*@__PURE__*/
  fileDesc("Cgl0ZHgucHJvdG8SA3RkeCK0AQoHUXVvdGVWNBIbCgZoZWFkZXIYASABKAsyCy50ZHguSGVhZGVyEicKDXRkX3F1b3RlX2JvZHkYAiABKAsyEC50ZHguVERRdW90ZUJvZHkSGAoQc2lnbmVkX2RhdGFfc2l6ZRgDIAEoDRI0CgtzaWduZWRfZGF0YRgEIAEoCzIfLnRkeC5FY2RzYTI1NkJpdFF1b3RlVjRBdXRoRGF0YRITCgtleHRyYV9ieXRlcxgFIAEoDCKTAQoGSGVhZGVyEg8KB3ZlcnNpb24YASABKA0SHAoUYXR0ZXN0YXRpb25fa2V5X3R5cGUYAiABKA0SEAoIdGVlX3R5cGUYAyABKA0SDgoGcWVfc3ZuGAQgASgMEg8KB3BjZV9zdm4YBSABKAwSFAoMcWVfdmVuZG9yX2lkGAYgASgMEhEKCXVzZXJfZGF0YRgHIAEoDCL9AQoLVERRdW90ZUJvZHkSEwoLdGVlX3RjYl9zdm4YASABKAwSDwoHbXJfc2VhbRgCIAEoDBIWCg5tcl9zaWduZXJfc2VhbRgDIAEoDBIXCg9zZWFtX2F0dHJpYnV0ZXMYBCABKAwSFQoNdGRfYXR0cmlidXRlcxgFIAEoDBIMCgR4ZmFtGAYgASgMEg0KBW1yX3RkGAcgASgMEhQKDG1yX2NvbmZpZ19pZBgIIAEoDBIQCghtcl9vd25lchgJIAEoDBIXCg9tcl9vd25lcl9jb25maWcYCiABKAwSDQoFcnRtcnMYCyADKAwSEwoLcmVwb3J0X2RhdGEYDCABKAwiggEKGkVjZHNhMjU2Qml0UXVvdGVWNEF1dGhEYXRhEhEKCXNpZ25hdHVyZRgBIAEoDBIdChVlY2RzYV9hdHRlc3RhdGlvbl9rZXkYAiABKAwSMgoSY2VydGlmaWNhdGlvbl9kYXRhGAMgASgLMhYudGR4LkNlcnRpZmljYXRpb25EYXRhIoYBChFDZXJ0aWZpY2F0aW9uRGF0YRIdChVjZXJ0aWZpY2F0ZV9kYXRhX3R5cGUYASABKA0SDAoEc2l6ZRgCIAEoDRJEChxxZV9yZXBvcnRfY2VydGlmaWNhdGlvbl9kYXRhGAMgASgLMh4udGR4LlFFUmVwb3J0Q2VydGlmaWNhdGlvbkRhdGEiyAEKGVFFUmVwb3J0Q2VydGlmaWNhdGlvbkRhdGESJQoJcWVfcmVwb3J0GAEgASgLMhIudGR4LkVuY2xhdmVSZXBvcnQSGwoTcWVfcmVwb3J0X3NpZ25hdHVyZRgCIAEoDBIlCgxxZV9hdXRoX2RhdGEYAyABKAsyDy50ZHguUWVBdXRoRGF0YRJAChpwY2tfY2VydGlmaWNhdGVfY2hhaW5fZGF0YRgEIAEoCzIcLnRkeC5QQ0tDZXJ0aWZpY2F0ZUNoYWluRGF0YSJeChdQQ0tDZXJ0aWZpY2F0ZUNoYWluRGF0YRIdChVjZXJ0aWZpY2F0ZV9kYXRhX3R5cGUYASABKA0SDAoEc2l6ZRgCIAEoDRIWCg5wY2tfY2VydF9jaGFpbhgDIAEoDCI0CgpRZUF1dGhEYXRhEhgKEHBhcnNlZF9kYXRhX3NpemUYASABKA0SDAoEZGF0YRgCIAEoDCL3AQoNRW5jbGF2ZVJlcG9ydBIPCgdjcHVfc3ZuGAEgASgMEhMKC21pc2Nfc2VsZWN0GAIgASgNEhEKCXJlc2VydmVkMRgDIAEoDBISCgphdHRyaWJ1dGVzGAQgASgMEhIKCm1yX2VuY2xhdmUYBSABKAwSEQoJcmVzZXJ2ZWQyGAYgASgMEhEKCW1yX3NpZ25lchgHIAEoDBIRCglyZXNlcnZlZDMYCCABKAwSEwoLaXN2X3Byb2RfaWQYCSABKA0SDwoHaXN2X3N2bhgKIAEoDRIRCglyZXNlcnZlZDQYCyABKAwSEwoLcmVwb3J0X2RhdGEYDCABKAxiBnByb3RvMw");

/**
 * @generated from message tdx.QuoteV4
 */
export type QuoteV4 = Message<"tdx.QuoteV4"> & {
  /**
   * @generated from field: tdx.Header header = 1;
   */
  header?: Header;

  /**
   * @generated from field: tdx.TDQuoteBody td_quote_body = 2;
   */
  tdQuoteBody?: TDQuoteBody;

  /**
   * @generated from field: uint32 signed_data_size = 3;
   */
  signedDataSize: number;

  /**
   * @generated from field: tdx.Ecdsa256BitQuoteV4AuthData signed_data = 4;
   */
  signedData?: Ecdsa256BitQuoteV4AuthData;

  /**
   * @generated from field: bytes extra_bytes = 5;
   */
  extraBytes: Uint8Array;
};

/**
 * Describes the message tdx.QuoteV4.
 * Use `create(QuoteV4Schema)` to create a new message.
 */
export const QuoteV4Schema: GenMessage<QuoteV4> = /*@__PURE__*/
  messageDesc(file_tdx, 0);

/**
 * @generated from message tdx.Header
 */
export type Header = Message<"tdx.Header"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from field: uint32 attestation_key_type = 2;
   */
  attestationKeyType: number;

  /**
   * @generated from field: uint32 tee_type = 3;
   */
  teeType: number;

  /**
   * @generated from field: bytes qe_svn = 4;
   */
  qeSvn: Uint8Array;

  /**
   * @generated from field: bytes pce_svn = 5;
   */
  pceSvn: Uint8Array;

  /**
   * @generated from field: bytes qe_vendor_id = 6;
   */
  qeVendorId: Uint8Array;

  /**
   * @generated from field: bytes user_data = 7;
   */
  userData: Uint8Array;
};

/**
 * Describes the message tdx.Header.
 * Use `create(HeaderSchema)` to create a new message.
 */
export const HeaderSchema: GenMessage<Header> = /*@__PURE__*/
  messageDesc(file_tdx, 1);

/**
 * @generated from message tdx.TDQuoteBody
 */
export type TDQuoteBody = Message<"tdx.TDQuoteBody"> & {
  /**
   * @generated from field: bytes tee_tcb_svn = 1;
   */
  teeTcbSvn: Uint8Array;

  /**
   * @generated from field: bytes mr_seam = 2;
   */
  mrSeam: Uint8Array;

  /**
   * @generated from field: bytes mr_signer_seam = 3;
   */
  mrSignerSeam: Uint8Array;

  /**
   * @generated from field: bytes seam_attributes = 4;
   */
  seamAttributes: Uint8Array;

  /**
   * @generated from field: bytes td_attributes = 5;
   */
  tdAttributes: Uint8Array;

  /**
   * @generated from field: bytes xfam = 6;
   */
  xfam: Uint8Array;

  /**
   * @generated from field: bytes mr_td = 7;
   */
  mrTd: Uint8Array;

  /**
   * @generated from field: bytes mr_config_id = 8;
   */
  mrConfigId: Uint8Array;

  /**
   * @generated from field: bytes mr_owner = 9;
   */
  mrOwner: Uint8Array;

  /**
   * @generated from field: bytes mr_owner_config = 10;
   */
  mrOwnerConfig: Uint8Array;

  /**
   * @generated from field: repeated bytes rtmrs = 11;
   */
  rtmrs: Uint8Array[];

  /**
   * @generated from field: bytes report_data = 12;
   */
  reportData: Uint8Array;
};

/**
 * Describes the message tdx.TDQuoteBody.
 * Use `create(TDQuoteBodySchema)` to create a new message.
 */
export const TDQuoteBodySchema: GenMessage<TDQuoteBody> = /*@__PURE__*/
  messageDesc(file_tdx, 2);

/**
 * @generated from message tdx.Ecdsa256BitQuoteV4AuthData
 */
export type Ecdsa256BitQuoteV4AuthData = Message<"tdx.Ecdsa256BitQuoteV4AuthData"> & {
  /**
   * @generated from field: bytes signature = 1;
   */
  signature: Uint8Array;

  /**
   * @generated from field: bytes ecdsa_attestation_key = 2;
   */
  ecdsaAttestationKey: Uint8Array;

  /**
   * @generated from field: tdx.CertificationData certification_data = 3;
   */
  certificationData?: CertificationData;
};

/**
 * Describes the message tdx.Ecdsa256BitQuoteV4AuthData.
 * Use `create(Ecdsa256BitQuoteV4AuthDataSchema)` to create a new message.
 */
export const Ecdsa256BitQuoteV4AuthDataSchema: GenMessage<Ecdsa256BitQuoteV4AuthData> = /*@__PURE__*/
  messageDesc(file_tdx, 3);

/**
 * @generated from message tdx.CertificationData
 */
export type CertificationData = Message<"tdx.CertificationData"> & {
  /**
   * @generated from field: uint32 certificate_data_type = 1;
   */
  certificateDataType: number;

  /**
   * @generated from field: uint32 size = 2;
   */
  size: number;

  /**
   * @generated from field: tdx.QEReportCertificationData qe_report_certification_data = 3;
   */
  qeReportCertificationData?: QEReportCertificationData;
};

/**
 * Describes the message tdx.CertificationData.
 * Use `create(CertificationDataSchema)` to create a new message.
 */
export const CertificationDataSchema: GenMessage<CertificationData> = /*@__PURE__*/
  messageDesc(file_tdx, 4);

/**
 * @generated from message tdx.QEReportCertificationData
 */
export type QEReportCertificationData = Message<"tdx.QEReportCertificationData"> & {
  /**
   * @generated from field: tdx.EnclaveReport qe_report = 1;
   */
  qeReport?: EnclaveReport;

  /**
   * @generated from field: bytes qe_report_signature = 2;
   */
  qeReportSignature: Uint8Array;

  /**
   * @generated from field: tdx.QeAuthData qe_auth_data = 3;
   */
  qeAuthData?: QeAuthData;

  /**
   * @generated from field: tdx.PCKCertificateChainData pck_certificate_chain_data = 4;
   */
  pckCertificateChainData?: PCKCertificateChainData;
};

/**
 * Describes the message tdx.QEReportCertificationData.
 * Use `create(QEReportCertificationDataSchema)` to create a new message.
 */
export const QEReportCertificationDataSchema: GenMessage<QEReportCertificationData> = /*@__PURE__*/
  messageDesc(file_tdx, 5);

/**
 * @generated from message tdx.PCKCertificateChainData
 */
export type PCKCertificateChainData = Message<"tdx.PCKCertificateChainData"> & {
  /**
   * @generated from field: uint32 certificate_data_type = 1;
   */
  certificateDataType: number;

  /**
   * @generated from field: uint32 size = 2;
   */
  size: number;

  /**
   * @generated from field: bytes pck_cert_chain = 3;
   */
  pckCertChain: Uint8Array;
};

/**
 * Describes the message tdx.PCKCertificateChainData.
 * Use `create(PCKCertificateChainDataSchema)` to create a new message.
 */
export const PCKCertificateChainDataSchema: GenMessage<PCKCertificateChainData> = /*@__PURE__*/
  messageDesc(file_tdx, 6);

/**
 * @generated from message tdx.QeAuthData
 */
export type QeAuthData = Message<"tdx.QeAuthData"> & {
  /**
   * @generated from field: uint32 parsed_data_size = 1;
   */
  parsedDataSize: number;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message tdx.QeAuthData.
 * Use `create(QeAuthDataSchema)` to create a new message.
 */
export const QeAuthDataSchema: GenMessage<QeAuthData> = /*@__PURE__*/
  messageDesc(file_tdx, 7);

/**
 * @generated from message tdx.EnclaveReport
 */
export type EnclaveReport = Message<"tdx.EnclaveReport"> & {
  /**
   * @generated from field: bytes cpu_svn = 1;
   */
  cpuSvn: Uint8Array;

  /**
   * @generated from field: uint32 misc_select = 2;
   */
  miscSelect: number;

  /**
   * @generated from field: bytes reserved1 = 3;
   */
  reserved1: Uint8Array;

  /**
   * @generated from field: bytes attributes = 4;
   */
  attributes: Uint8Array;

  /**
   * @generated from field: bytes mr_enclave = 5;
   */
  mrEnclave: Uint8Array;

  /**
   * @generated from field: bytes reserved2 = 6;
   */
  reserved2: Uint8Array;

  /**
   * @generated from field: bytes mr_signer = 7;
   */
  mrSigner: Uint8Array;

  /**
   * @generated from field: bytes reserved3 = 8;
   */
  reserved3: Uint8Array;

  /**
   * @generated from field: uint32 isv_prod_id = 9;
   */
  isvProdId: number;

  /**
   * @generated from field: uint32 isv_svn = 10;
   */
  isvSvn: number;

  /**
   * @generated from field: bytes reserved4 = 11;
   */
  reserved4: Uint8Array;

  /**
   * @generated from field: bytes report_data = 12;
   */
  reportData: Uint8Array;
};

/**
 * Describes the message tdx.EnclaveReport.
 * Use `create(EnclaveReportSchema)` to create a new message.
 */
export const EnclaveReportSchema: GenMessage<EnclaveReport> = /*@__PURE__*/
  messageDesc(file_tdx, 8);

